sudo: false
cache: bundler
bundler_args: ""
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.1.6
gemfile:
  - gemfiles/rails-3.0.gemfile
  - gemfiles/rails-3.2.gemfile
  - gemfiles/rails-4.0.gemfile
